/** Auto-generated by scripts/build-practice-raga-metadata.mjs — do not edit. */
export type PracticeRagaParentEntry = {
  parentMelakartaNum: number;
  isMelakarta: boolean;
};

/** Dataset fallback when `melakartaNum` is null on pool rāgas. */
export const PRACTICE_RAGA_PARENT_INDEX: Readonly<
  Record<string, PracticeRagaParentEntry>
> = {
  "Abheri": {
    "parentMelakartaNum": 20,
    "isMelakarta": false
  },
  "Abhogi": {
    "parentMelakartaNum": 22,
    "isMelakarta": false
  },
  "Ahiri": {
    "parentMelakartaNum": 17,
    "isMelakarta": false
  },
  "Anandabhairavi": {
    "parentMelakartaNum": 20,
    "isMelakarta": false
  },
  "Andolika": {
    "parentMelakartaNum": 28,
    "isMelakarta": false
  },
  "Arabhi": {
    "parentMelakartaNum": 26,
    "isMelakarta": false
  },
  "Saveri": {
    "parentMelakartaNum": 37,
    "isMelakarta": false
  },
  "Bageshri": {
    "parentMelakartaNum": 22,
    "isMelakarta": false
  },
  "Bahudari": {
    "parentMelakartaNum": 28,
    "isMelakarta": false
  },
  "Begada": {
    "parentMelakartaNum": 29,
    "isMelakarta": false
  },
  "Bhairavi": {
    "parentMelakartaNum": 20,
    "isMelakarta": false
  },
  "Bilahari": {
    "parentMelakartaNum": 29,
    "isMelakarta": false
  },
  "Chakravakam": {
    "parentMelakartaNum": 16,
    "isMelakarta": true
  },
  "Chalanata": {
    "parentMelakartaNum": 36,
    "isMelakarta": true
  },
  "Charukesi": {
    "parentMelakartaNum": 26,
    "isMelakarta": true
  },
  "Darbar": {
    "parentMelakartaNum": 29,
    "isMelakarta": false
  },
  "Darbarikanada": {
    "parentMelakartaNum": 20,
    "isMelakarta": false
  },
  "Devagandhari": {
    "parentMelakartaNum": 29,
    "isMelakarta": false
  },
  "Dhanyasi": {
    "parentMelakartaNum": 8,
    "isMelakarta": false
  },
  "Dharmavati": {
    "parentMelakartaNum": 59,
    "isMelakarta": true
  },
  "Ganamurti": {
    "parentMelakartaNum": 3,
    "isMelakarta": true
  },
  "Hamirkalyani": {
    "parentMelakartaNum": 65,
    "isMelakarta": false
  },
  "Hamsanandi": {
    "parentMelakartaNum": 53,
    "isMelakarta": false
  },
  "Harikambhoji": {
    "parentMelakartaNum": 28,
    "isMelakarta": true
  },
  "Hemavati": {
    "parentMelakartaNum": 58,
    "isMelakarta": true
  },
  "Hindolam": {
    "parentMelakartaNum": 8,
    "isMelakarta": false
  },
  "Huseni": {
    "parentMelakartaNum": 22,
    "isMelakarta": false
  },
  "Jaganmohini": {
    "parentMelakartaNum": 15,
    "isMelakarta": false
  },
  "Janaranjani": {
    "parentMelakartaNum": 29,
    "isMelakarta": false
  },
  "Kalavati": {
    "parentMelakartaNum": 31,
    "isMelakarta": false
  },
  "Kalyani": {
    "parentMelakartaNum": 64,
    "isMelakarta": false
  },
  "Kamalamanohari": {
    "parentMelakartaNum": 27,
    "isMelakarta": false
  },
  "Kambhoji": {
    "parentMelakartaNum": 28,
    "isMelakarta": false
  },
  "Kannada": {
    "parentMelakartaNum": 29,
    "isMelakarta": false
  },
  "Kapi": {
    "parentMelakartaNum": 22,
    "isMelakarta": false
  },
  "Kharaharapriya": {
    "parentMelakartaNum": 22,
    "isMelakarta": true
  },
  "KarnaRanjani": {
    "parentMelakartaNum": 22,
    "isMelakarta": false
  },
  "Kedaram": {
    "parentMelakartaNum": 29,
    "isMelakarta": false
  },
  "Keeravani": {
    "parentMelakartaNum": 21,
    "isMelakarta": true
  },
  "Khamas": {
    "parentMelakartaNum": 28,
    "isMelakarta": false
  },
  "Kuntalavarali": {
    "parentMelakartaNum": 28,
    "isMelakarta": false
  },
  "Madhuvanti": {
    "parentMelakartaNum": 59,
    "isMelakarta": false
  },
  "Malahari": {
    "parentMelakartaNum": 15,
    "isMelakarta": false
  },
  "Mandari": {
    "parentMelakartaNum": 51,
    "isMelakarta": false
  },
  "Manirangu": {
    "parentMelakartaNum": 22,
    "isMelakarta": false
  },
  "Mayamalavagowla": {
    "parentMelakartaNum": 15,
    "isMelakarta": true
  },
  "MohanaKalyani": {
    "parentMelakartaNum": 65,
    "isMelakarta": false
  },
  "Mohanam": {
    "parentMelakartaNum": 28,
    "isMelakarta": false
  },
  "Mukhari": {
    "parentMelakartaNum": 20,
    "isMelakarta": false
  },
  "Natabhairavi": {
    "parentMelakartaNum": 20,
    "isMelakarta": true
  },
  "Nayaki": {
    "parentMelakartaNum": 20,
    "isMelakarta": false
  },
  "Ramapriya": {
    "parentMelakartaNum": 52,
    "isMelakarta": true
  },
  "Ranjani": {
    "parentMelakartaNum": 31,
    "isMelakarta": false
  },
  "Rasikapriya": {
    "parentMelakartaNum": 72,
    "isMelakarta": true
  },
  "Revagupti": {
    "parentMelakartaNum": 15,
    "isMelakarta": false
  },
  "Revati": {
    "parentMelakartaNum": 2,
    "isMelakarta": false
  },
  "Sama": {
    "parentMelakartaNum": 29,
    "isMelakarta": false
  },
  "Saramati": {
    "parentMelakartaNum": 20,
    "isMelakarta": false
  },
  "Saranga": {
    "parentMelakartaNum": 64,
    "isMelakarta": false
  },
  "Sarasangi": {
    "parentMelakartaNum": 27,
    "isMelakarta": true
  },
  "Simhendramadhyamam": {
    "parentMelakartaNum": 57,
    "isMelakarta": true
  },
  "Sindhubhairavi": {
    "parentMelakartaNum": 10,
    "isMelakarta": false
  },
  "Shuddhadhanyasi": {
    "parentMelakartaNum": 20,
    "isMelakarta": false
  },
  "Shuddhasaveri": {
    "parentMelakartaNum": 29,
    "isMelakarta": false
  },
  "Vachaspati": {
    "parentMelakartaNum": 64,
    "isMelakarta": true
  },
  "Valaji": {
    "parentMelakartaNum": 28,
    "isMelakarta": false
  },
  "Vijayanagari": {
    "parentMelakartaNum": 59,
    "isMelakarta": false
  },
  "Yadukulakambhoji": {
    "parentMelakartaNum": 28,
    "isMelakarta": false
  },
  "Todi": {
    "parentMelakartaNum": 8,
    "isMelakarta": false
  },
  "Varali": {
    "parentMelakartaNum": 39,
    "isMelakarta": false
  },
  "Atana": {
    "parentMelakartaNum": 29,
    "isMelakarta": false
  },
  "Bhoopalam": {
    "parentMelakartaNum": 15,
    "isMelakarta": false
  },
  "Bowli": {
    "parentMelakartaNum": 15,
    "isMelakarta": false
  },
  "Brindavanasaranga": {
    "parentMelakartaNum": 22,
    "isMelakarta": false
  },
  "Chandrajyoti": {
    "parentMelakartaNum": 16,
    "isMelakarta": false
  },
  "Chandrakauns": {
    "parentMelakartaNum": 45,
    "isMelakarta": false
  },
  "Desh": {
    "parentMelakartaNum": 28,
    "isMelakarta": false
  },
  "Dwijavanti": {
    "parentMelakartaNum": 28,
    "isMelakarta": false
  },
  "Gambheeranattai": {
    "parentMelakartaNum": 36,
    "isMelakarta": false
  },
  "Gowlai": {
    "parentMelakartaNum": 15,
    "isMelakarta": false
  },
  "Hamsanaadam": {
    "parentMelakartaNum": 29,
    "isMelakarta": false
  },
  "Jayanthashri": {
    "parentMelakartaNum": 20,
    "isMelakarta": false
  },
  "Kaanada": {
    "parentMelakartaNum": 22,
    "isMelakarta": false
  },
  "Kadanakuthoohalam": {
    "parentMelakartaNum": 28,
    "isMelakarta": false
  },
  "Kalyanavasantham": {
    "parentMelakartaNum": 21,
    "isMelakarta": false
  },
  "Kannadagowlai": {
    "parentMelakartaNum": 28,
    "isMelakarta": false
  },
  "Kedaragowlai": {
    "parentMelakartaNum": 28,
    "isMelakarta": false
  },
  "Lalitha": {
    "parentMelakartaNum": 15,
    "isMelakarta": false
  },
  "Maand": {
    "parentMelakartaNum": 28,
    "isMelakarta": false
  },
  "Malayamarutham": {
    "parentMelakartaNum": 16,
    "isMelakarta": false
  },
  "Nagaswarali": {
    "parentMelakartaNum": 15,
    "isMelakarta": false
  },
  "Nalinakanthi": {
    "parentMelakartaNum": 29,
    "isMelakarta": false
  },
  "Nattai": {
    "parentMelakartaNum": 36,
    "isMelakarta": false
  },
  "Natakurinji": {
    "parentMelakartaNum": 28,
    "isMelakarta": false
  },
  "NavarasaKanada": {
    "parentMelakartaNum": 22,
    "isMelakarta": false
  },
  "Neelambari": {
    "parentMelakartaNum": 29,
    "isMelakarta": false
  },
  "Neelimathi": {
    "parentMelakartaNum": 22,
    "isMelakarta": false
  },
  "Panthuvarali": {
    "parentMelakartaNum": 51,
    "isMelakarta": false
  },
  "Poornachandrika": {
    "parentMelakartaNum": 29,
    "isMelakarta": false
  },
  "Poorvikalyani": {
    "parentMelakartaNum": 53,
    "isMelakarta": false
  },
  "Rathipathipriya": {
    "parentMelakartaNum": 22,
    "isMelakarta": false
  },
  "Saraswathi": {
    "parentMelakartaNum": 64,
    "isMelakarta": false
  },
  "Sri": {
    "parentMelakartaNum": 22,
    "isMelakarta": false
  },
  "Sivaranjani": {
    "parentMelakartaNum": 20,
    "isMelakarta": false
  },
  "Sowrashtram": {
    "parentMelakartaNum": 28,
    "isMelakarta": false
  },
  "Sriranjani": {
    "parentMelakartaNum": 22,
    "isMelakarta": false
  },
  "Subhapantuvarali": {
    "parentMelakartaNum": 45,
    "isMelakarta": true
  },
  "Sumanesaranjani": {
    "parentMelakartaNum": 28,
    "isMelakarta": false
  },
  "Sunandavinodini": {
    "parentMelakartaNum": 29,
    "isMelakarta": false
  },
  "Suruti": {
    "parentMelakartaNum": 28,
    "isMelakarta": false
  },
  "Surya": {
    "parentMelakartaNum": 29,
    "isMelakarta": false
  },
  "Thilang": {
    "parentMelakartaNum": 28,
    "isMelakarta": false
  },
  "Varamu": {
    "parentMelakartaNum": 15,
    "isMelakarta": false
  },
  "Vasantha": {
    "parentMelakartaNum": 17,
    "isMelakarta": false
  },
  "Vasanthi": {
    "parentMelakartaNum": 17,
    "isMelakarta": false
  }
} as const;
