/**
 * Authoritative arohanam / avarohanam for the scale quiz only (Unicode swaras, Ṡ = tara Sa).
 * Merged after QUIZ_RAGAS in scale-quiz-ragas.ts.
 */

export type ScaleQuizScaleOverride = {
  name: string;
  melakartaNum: number | null;
  arohanam: string;
  avarohanam: string;
};

/** id → scale (adds new ragas to the pool or replaces aro/ava for existing ids). */
export const SCALE_QUIZ_SCALE_OVERRIDES: Record<string, ScaleQuizScaleOverride> = {
  Abheri: {
    name: "Abheri",
    melakartaNum: 22,
    arohanam: "S G₂ M₁ P N₂ Ṡ",
    avarohanam: "Ṡ N₂ D₂ P M₁ G₂ R₂ S",
  },
  Abhogi: {
    name: "Abhogi",
    melakartaNum: null,
    arohanam: "S R₂ G₂ M₁ D₂ Ṡ",
    avarohanam: "Ṡ D₂ M₁ G₂ R₂ S",
  },
  Ahiri: {
    name: "Ahiri",
    melakartaNum: null,
    arohanam: "S R₁ S G₃ M₁ P D₁ N₂ Ṡ",
    avarohanam: "Ṡ N₂ D₁ P M₁ G₃ R₁ S",
  },
  Amritavarshini: {
    name: "Amritavarshini",
    melakartaNum: 53,
    arohanam: "S G₃ M₂ P N₃ Ṡ",
    avarohanam: "Ṡ N₃ P M₂ G₃ S",
  },
  Anandabhairavi: {
    name: "Anandabhairavi",
    melakartaNum: 20,
    arohanam: "S G₂ R₂ G₂ M₁ P D₂ P Ṡ",
    avarohanam: "Ṡ N₂ D₂ P M₁ G₂ R₂ S",
  },
  Andolika: {
    name: "Andolika",
    melakartaNum: null,
    arohanam: "S R₂ M₁ P N₂ Ṡ",
    avarohanam: "Ṡ N₂ D₂ M₁ R₂ S",
  },
  Arabhi: {
    name: "Arabhi",
    melakartaNum: null,
    arohanam: "S R₂ M₁ P D₂ Ṡ",
    avarohanam: "Ṡ N₃ D₂ P M₁ G₃ R₂ S",
  },
  Saveri: {
    name: "Saveri",
    melakartaNum: null,
    arohanam: "S R₁ M₁ P D₁ Ṡ",
    avarohanam: "Ṡ N₃ D₁ P M₁ G₃ R₁ S",
  },
  Atana: {
    name: "Atana",
    melakartaNum: null,
    arohanam: "S R₂ M₁ P N₃ Ṡ",
    avarohanam: "Ṡ N₃ S D₂ P M₁ R₂ G₃ R₂ S",
  },
  Bageshri: {
    name: "Bageshri",
    melakartaNum: null,
    arohanam: "S G₂ M₁ D₂ N₂ Ṡ",
    avarohanam: "Ṡ N₂ D₂ M₁ P G₂ M₁ R₂ S",
  },
  Bahudari: {
    name: "Bahudari",
    melakartaNum: null,
    arohanam: "S G₃ M₁ P D₂ N₂ Ṡ",
    avarohanam: "Ṡ N₂ P M₁ G₃ S",
  },
  Begada: {
    name: "Begada",
    melakartaNum: 29,
    arohanam: "S G₃ R₂ G₃ M₁ P D₂ P Ṡ",
    avarohanam: "Ṡ N₃ D₂ P M₁ G₃ R₂ S",
  },
  Bhairavi: {
    name: "Bhairavi",
    melakartaNum: 20,
    arohanam: "S G₂ R₂ G₂ M₁ P D₂ N₂ Ṡ",
    avarohanam: "Ṡ N₂ D₁ P M₁ G₂ R₂ S",
  },
  Bhoopalam: {
    name: "Bhoopalam",
    melakartaNum: null,
    arohanam: "S R₁ G₂ P D₁ Ṡ",
    avarohanam: "Ṡ D₁ P G₂ R₁ S",
  },
  Bilahari: {
    name: "Bilahari",
    melakartaNum: null,
    arohanam: "S R₂ G₃ P D₂ Ṡ",
    avarohanam: "Ṡ N₃ D₂ P M₁ G₃ R₂ S",
  },
  Bowli: {
    name: "Bowli",
    melakartaNum: null,
    arohanam: "S R₁ G₃ P D₁ Ṡ",
    avarohanam: "Ṡ N₃ D₁ P G₃ R₁ S",
  },
  Brindavanasaranga: {
    name: "Brindavana Saranga",
    melakartaNum: null,
    arohanam: "S R₂ M₁ P N₃ Ṡ",
    avarohanam: "Ṡ N₂ P M₁ R₂ G₂ S",
  },
  Chakravakam: {
    name: "Chakravakam",
    melakartaNum: 16,
    arohanam: "S R₁ G₃ M₁ P D₂ N₂ Ṡ",
    avarohanam: "Ṡ N₂ D₂ P M₁ G₃ R₁ S",
  },
  Chalanata: {
    name: "Chala Nattai",
    melakartaNum: 36,
    arohanam: "S R₃ G₃ M₁ P D₃ N₃ Ṡ",
    avarohanam: "Ṡ N₃ D₃ P M₁ G₃ R₃ S",
  },
  Chandrajyoti: {
    name: "Chandrajyoti",
    melakartaNum: null,
    arohanam: "S R₁ G₁ M₂ P D₂ Ṡ",
    avarohanam: "Ṡ D₂ P M₂ G₁ R₁ S",
  },
  Chandrakauns: {
    name: "Chandrakauns",
    melakartaNum: null,
    arohanam: "S G₂ M₁ D₁ N₃ Ṡ",
    avarohanam: "Ṡ N₃ D₁ M₁ G₂ S",
  },
  Charukesi: {
    name: "Charukesi",
    melakartaNum: 26,
    arohanam: "S R₂ G₃ M₁ P D₁ N₂ Ṡ",
    avarohanam: "Ṡ N₂ D₁ P M₁ G₃ R₂ S",
  },
  Darbar: {
    name: "Darbar",
    melakartaNum: null,
    arohanam: "S R₂ M₁ P D₂ N₂ Ṡ",
    avarohanam: "Ṡ N₂ S D₂ P M₁ R₂ G₂ G₂ R₂ S",
  },
  Darbarikanada: {
    name: "Darbari Kanada",
    melakartaNum: null,
    arohanam: "S R₂ G₂ M₁ P D₁ N₂ Ṡ",
    avarohanam: "Ṡ D₁ N₂ P M₁ P G₂ M₁ R₂ S",
  },
  Desh: {
    name: "Desh",
    melakartaNum: null,
    arohanam: "S R₂ M₁ P N₃ Ṡ",
    avarohanam: "Ṡ N₂ D₂ P M₁ G₃ R₂ S",
  },
  Devagandhari: {
    name: "Devagandhari",
    melakartaNum: null,
    arohanam: "S R₂ M₁ P D₂ Ṡ",
    avarohanam: "Ṡ N₃ D₂ N₂ D₂ P M₁ G₃ R₂ S",
  },
  Dhanyasi: {
    name: "Dhanyasi",
    melakartaNum: null,
    arohanam: "S G₂ M₁ P N₂ Ṡ",
    avarohanam: "Ṡ N₂ D₁ P M₁ G₂ R₁ S",
  },
  Dharmavati: {
    name: "Dharmavati",
    melakartaNum: 59,
    arohanam: "S R₂ G₂ M₂ P D₂ N₃ Ṡ",
    avarohanam: "Ṡ N₃ D₂ P M₂ G₂ R₂ S",
  },
  Dwijavanti: {
    name: "Dwijavanti",
    melakartaNum: null,
    arohanam: "S R₂ G₃ M₁ P D₂ Ṡ",
    avarohanam: "Ṡ N₂ D₂ P M₁ G₃ M₁ R₂ G₂ R₂ S",
  },
  Gambheeranattai: {
    name: "Gambheera Nattai",
    melakartaNum: null,
    arohanam: "S G₃ M₁ P N₃ Ṡ",
    avarohanam: "Ṡ N₃ P M₁ G₃ S",
  },
  Ganamurti: {
    name: "Ganamoorthi",
    melakartaNum: 3,
    arohanam: "S R₁ G₁ M₁ P D₁ N₃ Ṡ",
    avarohanam: "Ṡ N₃ D₁ P M₁ G₁ R₁ S",
  },
  Gowlai: {
    name: "Gowlai",
    melakartaNum: null,
    arohanam: "S R₁ M₁ P N₃ Ṡ",
    avarohanam: "Ṡ N₃ P M₁ G₃ M₁ R₁ G₃ M₁ R₁ S",
  },
  Hamirkalyani: {
    name: "Hamir Kalyani",
    melakartaNum: null,
    arohanam: "S P M₂ P D₂ N₃ Ṡ",
    avarohanam: "Ṡ N₃ D₂ P M₂ M₁ G₃ P M₁ R₂ S",
  },
  Hamsadhwani: {
    name: "Hamsadhwani",
    melakartaNum: 29,
    arohanam: "S R₂ G₃ P N₃ Ṡ",
    avarohanam: "Ṡ N₃ P G₃ R₂ S",
  },
  Hamsanaadam: {
    name: "Hamsanadam",
    melakartaNum: null,
    arohanam: "S R₂ M₂ P N₃ Ṡ",
    avarohanam: "Ṡ N₃ P M₂ R₂ S",
  },
  Hamsanandi: {
    name: "Hamsanandi",
    melakartaNum: null,
    arohanam: "S R₁ G₃ M₂ D₂ N₃ Ṡ",
    avarohanam: "Ṡ N₃ D₂ M₂ G₃ R₁ S",
  },
  Harikambhoji: {
    name: "Hari Kambhoji",
    melakartaNum: 28,
    arohanam: "S R₂ G₃ M₁ P D₂ N₂ Ṡ",
    avarohanam: "Ṡ N₂ D₂ P M₁ G₃ R₂ S",
  },
  Hemavati: {
    name: "Hemavati",
    melakartaNum: 58,
    arohanam: "S R₂ G₂ M₂ P D₂ N₂ Ṡ",
    avarohanam: "Ṡ N₂ D₂ P M₂ G₂ R₂ S",
  },
  Hindolam: {
    name: "Hindolam",
    melakartaNum: 20,
    arohanam: "S G₂ M₁ D₁ N₂ Ṡ",
    avarohanam: "Ṡ N₂ D₁ M₁ G₂ S",
  },
  Huseni: {
    name: "Huseni",
    melakartaNum: null,
    arohanam: "S R₂ G₂ M₁ P N₂ D₂ N₂ Ṡ",
    avarohanam: "Ṡ N₂ D₁ P M₁ G₂ R₂ S",
  },
  Jaganmohini: {
    name: "Jaganmohini",
    melakartaNum: null,
    arohanam: "S G₃ M₁ P N₃ Ṡ",
    avarohanam: "Ṡ N₃ P M₁ G₃ R₁ S",
  },
  Janaranjani: {
    name: "Janaranjani",
    melakartaNum: null,
    arohanam: "S R₂ G₃ M₁ P D₂ P N₃ Ṡ",
    avarohanam: "Ṡ D₂ P M₁ R₂ S",
  },
  Jayanthashri: {
    name: "Jayanthashri",
    melakartaNum: null,
    arohanam: "S G₂ M₁ D₁ N₂ Ṡ",
    avarohanam: "Ṡ N₂ D₁ M₁ P M₁ G₂ S",
  },
  Kadanakuthoohalam: {
    name: "Kadanakuthoohalam",
    melakartaNum: null,
    arohanam: "S R₂ M₁ D₂ N₃ G₃ P Ṡ",
    avarohanam: "Ṡ N₃ D₂ P M₁ G₃ R₂ S",
  },
  Kalavati: {
    name: "Kalavati",
    melakartaNum: null,
    arohanam: "S R₁ M₁ P D₂ Ṡ",
    avarohanam: "Ṡ D₂ P M₁ G₃ S R₁ D₂ S",
  },
  Kalyanavasantham: {
    name: "Kalyana Vasantham",
    melakartaNum: null,
    arohanam: "S G₂ M₁ D₁ N₃ Ṡ",
    avarohanam: "Ṡ N₃ D₁ P M₁ G₂ R₂ S",
  },
  Kalyani: {
    name: "Kalyani",
    melakartaNum: 65,
    arohanam: "S R₂ G₃ M₂ P D₂ N₃ Ṡ",
    avarohanam: "Ṡ N₃ D₂ P M₂ G₃ R₂ S",
  },
  Kamalamanohari: {
    name: "Kamala Manohari",
    melakartaNum: null,
    arohanam: "S G₃ M₁ P N₃ Ṡ",
    avarohanam: "Ṡ N₃ D₁ P M₁ G₃ S",
  },
  Kambhoji: {
    name: "Kambhoji",
    melakartaNum: null,
    arohanam: "S R₂ G₃ M₁ P D₂ Ṡ",
    avarohanam: "Ṡ N₂ D₂ P M₁ G₃ R₂ S",
  },
  Kannada: {
    name: "Kannada",
    melakartaNum: null,
    arohanam: "S G₃ M₁ P M₁ D₂ N₃ Ṡ",
    avarohanam: "Ṡ D₂ P M₁ G₃ M₁ R₂ S",
  },
  Kannadagowlai: {
    name: "Kannada Gowlai",
    melakartaNum: null,
    arohanam: "S R₂ G₂ M₁ P N₂ Ṡ",
    avarohanam: "Ṡ N₂ D₂ P M₁ G₂ S",
  },
  Kapi: {
    name: "Kapi",
    melakartaNum: null,
    arohanam: "S R₂ M₁ P N₃ Ṡ",
    avarohanam: "Ṡ N₂ D₂ N₂ P M₁ G₂ R₂ S",
  },
  Karaharapriya: {
    name: "Karaharapriya",
    melakartaNum: 22,
    arohanam: "S R₂ G₂ M₁ P D₂ N₂ Ṡ",
    avarohanam: "Ṡ N₂ D₂ P M₁ G₂ R₂ S",
  },
  Kharaharapriya: {
    name: "Kharaharapriya",
    melakartaNum: 22,
    arohanam: "S R₂ G₂ M₁ P D₂ N₂ Ṡ",
    avarohanam: "Ṡ N₂ D₂ P M₁ G₂ R₂ S",
  },
  KarnaRanjani: {
    name: "Karna Ranjani",
    melakartaNum: null,
    arohanam: "S R₂ G₂ M₁ G₂ P D₂ Ṡ",
    avarohanam: "Ṡ N₂ D₂ P M₁ G₂ R₂ S",
  },
  Kedaragowlai: {
    name: "Kedara Gowlai",
    melakartaNum: null,
    arohanam: "S R₂ M₁ P N₂ Ṡ",
    avarohanam: "Ṡ N₂ D₂ P M₁ G₃ R₂ S",
  },
  Kaanada: {
    name: "Kaanada",
    melakartaNum: null,
    arohanam: "S R₂ P G₂ M₁ D₂ N₂ Ṡ",
    avarohanam: "Ṡ N₂ P M₁ G₂ M₁ R₂ S",
  },
  Kedaram: {
    name: "Kedaram",
    melakartaNum: null,
    arohanam: "S M₁ G₃ M₁ P N₃ Ṡ",
    avarohanam: "Ṡ N₃ P M₁ G₃ R₂ S",
  },
  Keeravani: {
    name: "Keeravani",
    melakartaNum: 21,
    arohanam: "S R₂ G₂ M₁ P D₁ N₃ Ṡ",
    avarohanam: "Ṡ N₃ D₁ P M₁ G₂ R₂ S",
  },
  Khamas: {
    name: "Khamas",
    melakartaNum: null,
    arohanam: "S M₁ G₃ M₁ P D₂ N₂ Ṡ",
    avarohanam: "Ṡ N₂ D₂ P M₁ G₃ R₂ S",
  },
  Kuntalavarali: {
    name: "Kuntalavarali",
    melakartaNum: null,
    arohanam: "S M₁ P D₂ N₂ D₂ Ṡ",
    avarohanam: "Ṡ N₂ D₂ P M₁ S",
  },
  Lalitha: {
    name: "Lalitha",
    melakartaNum: null,
    arohanam: "S R₁ G₃ M₁ D₁ N₃ Ṡ",
    avarohanam: "Ṡ N₃ D₁ M₁ G₃ R₁ S",
  },
  Lathangi: {
    name: "Lathangi",
    melakartaNum: 38,
    arohanam: "S R₂ G₃ M₂ P D₁ N₃ Ṡ",
    avarohanam: "Ṡ N₃ D₁ P M₂ G₃ R₂ S",
  },
  Maand: {
    name: "Maand",
    melakartaNum: null,
    arohanam: "S G₃ M₁ D₂ N₃ Ṡ",
    avarohanam: "Ṡ N₃ D₂ P M₁ G₃ R₂ S",
  },
  Madhuvanti: {
    name: "Madhuvanti",
    melakartaNum: null,
    arohanam: "S G₂ M₂ P N₃ Ṡ",
    avarohanam: "Ṡ N₃ D₂ P M₂ G₂ R₂ S",
  },
  Madhyamavathi: {
    name: "Madhyamavathi",
    melakartaNum: 22,
    arohanam: "S R₂ M₁ P N₂ Ṡ",
    avarohanam: "Ṡ N₂ P M₁ R₂ S",
  },
  Malahari: {
    name: "Malahari",
    melakartaNum: null,
    arohanam: "S R₁ M₁ P D₁ Ṡ",
    avarohanam: "Ṡ D₁ P M₁ G₃ R₁ S",
  },
  Malayamarutham: {
    name: "Malayamarutham",
    melakartaNum: null,
    arohanam: "S R₁ G₃ P D₂ N₂ Ṡ",
    avarohanam: "Ṡ N₂ D₂ P G₃ R₁ S",
  },
  Mandari: {
    name: "Mandari",
    melakartaNum: null,
    arohanam: "S R₁ G₃ M₂ P N₃ Ṡ",
    avarohanam: "Ṡ N₃ P M₂ G₃ R₁ S",
  },
  Manirangu: {
    name: "Manirangu",
    melakartaNum: null,
    arohanam: "S R₂ M₁ P N₂ Ṡ",
    avarohanam: "Ṡ N₂ P M₁ G₂ R₂ S",
  },
  Mayamalavagowla: {
    name: "Mayamalavagowla",
    melakartaNum: 15,
    arohanam: "S R₁ G₃ M₁ P D₁ N₃ Ṡ",
    avarohanam: "Ṡ N₃ D₁ P M₁ G₃ R₁ S",
  },
  MohanaKalyani: {
    name: "Mohana Kalyani",
    melakartaNum: null,
    arohanam: "S R₂ G₃ P D₂ Ṡ",
    avarohanam: "Ṡ N₃ D₂ P M₂ G₃ R₂ S",
  },
  Mohanam: {
    name: "Mohanam",
    melakartaNum: 28,
    arohanam: "S R₂ G₃ P D₂ Ṡ",
    avarohanam: "Ṡ D₂ P G₃ R₂ S",
  },
  Mukhari: {
    name: "Mukhari",
    melakartaNum: null,
    arohanam: "S R₂ M₁ P N₂ D₂ Ṡ",
    avarohanam: "Ṡ N₂ D₁ P M₁ G₂ R₂ S",
  },
  Nagaswarali: {
    name: "Nagaswarali",
    melakartaNum: null,
    arohanam: "S G₃ M₁ P D₂ Ṡ",
    avarohanam: "Ṡ D₂ P M₁ G₃ S",
  },
  Nalinakanthi: {
    name: "Nalinakanthi",
    melakartaNum: null,
    arohanam: "S G₃ R₂ M₁ P N₃ Ṡ",
    avarohanam: "Ṡ N₃ P M₁ G₃ R₂ S",
  },
  Nasikabhooshani: {
    name: "Nasikabhooshani",
    melakartaNum: 70,
    arohanam: "S R₃ G₃ M₂ P D₂ N₂ Ṡ",
    avarohanam: "Ṡ N₂ D₂ P M₂ G₃ R₃ S",
  },
  Natabhairavi: {
    name: "Natabhairavi",
    melakartaNum: 10,
    arohanam: "S R₂ G₂ M₁ P D₁ N₂ Ṡ",
    avarohanam: "Ṡ N₂ D₁ P M₁ G₂ R₂ S",
  },
  Natakurinji: {
    name: "Nattai Kurinji",
    melakartaNum: null,
    arohanam: "S R₂ G₃ M₁ N₂ D₂ N₂ P D₂ N₂ Ṡ",
    avarohanam: "Ṡ N₂ D₂ M₁ G₃ M₁ P G₃ R₂ S",
  },
  Nattai: {
    name: "Nattai",
    melakartaNum: null,
    arohanam: "S R₃ G₃ M₁ P D₃ N₃ Ṡ",
    avarohanam: "Ṡ N₃ P M₁ G₃ M₁ R₃ S",
  },
  NavarasaKanada: {
    name: "Navarasa Kanada",
    melakartaNum: null,
    arohanam: "S G₃ M₁ P Ṡ",
    avarohanam: "Ṡ N₂ D₂ M₁ G₃ R₂ S",
  },
  Nayaki: {
    name: "Nayaki",
    melakartaNum: null,
    arohanam: "S R₂ M₁ P D₂ N₂ D₂ P Ṡ",
    avarohanam: "Ṡ N₂ S P D₂ N₂ D₂ P M₁ R₂ G₂ R₂ S",
  },
  Neelambari: {
    name: "Neelambari",
    melakartaNum: null,
    arohanam: "S G₃ M₁ P N₃ Ṡ",
    avarohanam: "Ṡ N₃ P D₂ N₂ P M₁ G₃ R₂ M₁ G₃ S",
  },
  Neelimathi: {
    name: "Neelimathi",
    melakartaNum: null,
    arohanam: "S R₂ G₂ M₂ P D₃ N₃ Ṡ",
    avarohanam: "Ṡ N₃ D₃ P M₂ G₂ R₂ S",
  },
  Panthuvarali: {
    name: "Pantuvarali",
    melakartaNum: null,
    arohanam: "S R₁ G₃ M₂ P D₁ N₃ Ṡ",
    avarohanam: "Ṡ N₃ D₁ P M₂ G₃ R₁ S",
  },
  Poornachandrika: {
    name: "Poornachandrika",
    melakartaNum: null,
    arohanam: "S R₂ G₃ M₁ P D₂ P Ṡ",
    avarohanam: "Ṡ N₃ P M₁ R₂ G₃ M₁ R₂ S",
  },
  Poorvikalyani: {
    name: "Poorvikalyani",
    melakartaNum: null,
    arohanam: "S R₁ G₃ M₂ P D₂ P Ṡ",
    avarohanam: "Ṡ N₃ D₂ P M₂ G₃ R₁ S",
  },
  Ramapriya: {
    name: "Ramapriya",
    melakartaNum: 52,
    arohanam: "S R₁ G₃ M₂ P D₂ N₂ Ṡ",
    avarohanam: "Ṡ N₂ D₂ P M₂ G₃ R₁ S",
  },
  Ranjani: {
    name: "Ranjani",
    melakartaNum: null,
    arohanam: "S R₂ G₂ M₂ D₂ Ṡ",
    avarohanam: "Ṡ N₃ D₂ M₂ G₂ S R₂ G₂ S",
  },
  Rasikapriya: {
    name: "Rasikapriya",
    melakartaNum: 72,
    arohanam: "S R₁ G₃ M₂ P D₂ N₂ Ṡ",
    avarohanam: "Ṡ N₂ D₂ P M₂ G₃ R₁ S",
  },
  Rathipathipriya: {
    name: "Rathipathipriya",
    melakartaNum: null,
    arohanam: "S R₂ G₂ P N₂ Ṡ",
    avarohanam: "Ṡ N₂ P G₂ R₂ S",
  },
  Reethigowla: {
    name: "Reethigowla",
    melakartaNum: 22,
    arohanam: "S G₂ R₂ G₂ M₁ N₂ N₂ Ṡ",
    avarohanam: "Ṡ N₂ D₂ M₁ G₂ M₁ P M₁ G₂ R₂ S",
  },
  Revagupti: {
    name: "Revagupti",
    melakartaNum: null,
    arohanam: "S R₁ G₃ P D₁ Ṡ",
    avarohanam: "Ṡ D₁ P G₃ R₁ S",
  },
  Revati: {
    name: "Revati",
    melakartaNum: null,
    arohanam: "S R₁ M₁ P N₂ Ṡ",
    avarohanam: "Ṡ N₂ P M₁ R₁ S",
  },
  Sahana: {
    name: "Sahana",
    melakartaNum: 28,
    arohanam: "S R₂ G₃ M₁ P M₁ D₂ N₂ Ṡ",
    avarohanam: "Ṡ N₂ D₂ P M₁ G₃ M₁ R₂ G₃ R₂ S",
  },
  Sama: {
    name: "Sama",
    melakartaNum: null,
    arohanam: "S R₂ M₁ P D₂ Ṡ",
    avarohanam: "Ṡ D₂ P M₁ G₃ R₂ S",
  },
  Saramati: {
    name: "Saramati",
    melakartaNum: null,
    arohanam: "S R₂ G₂ M₁ P D₁ N₂ Ṡ",
    avarohanam: "Ṡ N₂ D₁ M₁ G₂ S",
  },
  Saranga: {
    name: "Saranga",
    melakartaNum: null,
    arohanam: "S P M₂ P D₂ N₃ Ṡ",
    avarohanam: "Ṡ D₂ P M₂ R₂ G₃ M₁ R₂ S",
  },
  Sarasangi: {
    name: "Sarasangi",
    melakartaNum: 31,
    arohanam: "S R₂ G₃ M₁ P D₁ N₃ Ṡ",
    avarohanam: "Ṡ N₃ D₁ P M₁ G₃ R₂ S",
  },
  Saraswathi: {
    name: "Saraswathi",
    melakartaNum: null,
    arohanam: "S R₂ M₂ P D₂ Ṡ",
    avarohanam: "Ṡ N₂ D₂ P M₂ R₂ S",
  },
  Sankarabharanam: {
    name: "Shankarabaranam",
    melakartaNum: 29,
    arohanam: "S R₂ G₃ M₁ P D₂ N₃ Ṡ",
    avarohanam: "Ṡ N₃ D₂ P M₁ G₃ R₂ S",
  },
  Shanmukapriya: {
    name: "Shanmukhapriya",
    melakartaNum: 56,
    arohanam: "S R₂ G₂ M₂ P D₁ N₂ Ṡ",
    avarohanam: "Ṡ N₂ D₁ P M₂ G₂ R₂ S",
  },
  Sri: {
    name: "Shri Ragam",
    melakartaNum: null,
    arohanam: "S R₂ M₁ P N₂ Ṡ",
    avarohanam: "Ṡ N₂ P D₂ N₂ P M₁ R₂ G₂ R₂ S",
  },
  Simhendramadhyamam: {
    name: "Simhendramadhyamam",
    melakartaNum: 57,
    arohanam: "S R₂ G₂ M₂ P D₁ N₃ Ṡ",
    avarohanam: "Ṡ N₃ D₁ P M₂ G₂ R₂ S",
  },
  Sindhubhairavi: {
    name: "Sindhubhairavi",
    melakartaNum: 10,
    arohanam: "S R₁ G₂ M₁ P D₁ N₂ Ṡ",
    avarohanam: "Ṡ N₂ D₁ P M₁ G₂ R₁ S",
  },
  Sivaranjani: {
    name: "Sivaranjani",
    melakartaNum: null,
    arohanam: "S R₂ G₂ P D₂ Ṡ",
    avarohanam: "Ṡ D₂ P G₂ R₂ S",
  },
  Sowrashtram: {
    name: "Sowrashtram",
    melakartaNum: null,
    arohanam: "S R₁ G₃ M₁ P M₁ D₂ N₃ Ṡ",
    avarohanam: "Ṡ N₃ D₂ N₂ D₂ P M₁ G₃ R₁ S",
  },
  Sriranjani: {
    name: "Sriranjani",
    melakartaNum: null,
    arohanam: "S R₂ G₂ M₁ D₂ N₂ Ṡ",
    avarohanam: "Ṡ N₂ D₂ M₁ G₂ R₂ S",
  },
  Subhapantuvarali: {
    name: "Subha Pantuvarali",
    melakartaNum: null,
    arohanam: "S R₁ G₂ M₂ P D₁ N₃ Ṡ",
    avarohanam: "Ṡ N₃ D₁ P M₂ G₂ R₁ S",
  },
  Shuddhadhanyasi: {
    name: "Suddha Dhanyasi",
    melakartaNum: null,
    arohanam: "S G₂ M₁ P N₂ Ṡ",
    avarohanam: "Ṡ N₂ P M₁ G₂ S",
  },
  Shuddhasaveri: {
    name: "Suddha Saveri",
    melakartaNum: null,
    arohanam: "S R₂ M₁ P D₂ Ṡ",
    avarohanam: "Ṡ D₂ P M₁ R₂ S",
  },
  Sumanesaranjani: {
    name: "Sumanesaranjani",
    melakartaNum: null,
    arohanam: "S G₂ M₂ P N₂ Ṡ",
    avarohanam: "Ṡ N₂ P M₂ G₂ S",
  },
  Sunandavinodini: {
    name: "Sunandavinodini",
    melakartaNum: null,
    arohanam: "S G₃ M₂ D₂ N₃ Ṡ",
    avarohanam: "Ṡ N₃ D₂ M₂ G₃ S",
  },
  Suruti: {
    name: "Surutti",
    melakartaNum: null,
    arohanam: "S R₂ M₁ P N₂ D₂ N₂ Ṡ",
    avarohanam: "Ṡ N₂ D₂ P M₁ G₃ P M₁ R₂ S",
  },
  Surya: {
    name: "Surya",
    melakartaNum: null,
    arohanam: "S G₃ M₁ D₁ N₂ Ṡ",
    avarohanam: "Ṡ N₂ D₁ M₁ G₃ S",
  },
  Thilang: {
    name: "Thilang",
    melakartaNum: null,
    arohanam: "S G₃ M₁ P N₃ Ṡ",
    avarohanam: "Ṡ N₂ P M₁ G₃ S",
  },
  Thodi: {
    name: "Thodi",
    melakartaNum: 8,
    arohanam: "S R₁ G₂ M₁ P D₁ N₂ Ṡ",
    avarohanam: "Ṡ N₂ D₁ P M₁ G₂ R₁ S",
  },
  Vachaspati: {
    name: "Vachaspati",
    melakartaNum: 64,
    arohanam: "S R₂ G₃ M₂ P D₂ N₂ Ṡ",
    avarohanam: "Ṡ N₂ D₂ P M₂ G₃ R₂ S",
  },
  Valaji: {
    name: "Valaji",
    melakartaNum: null,
    arohanam: "S G₃ P D₂ N₂ Ṡ",
    avarohanam: "Ṡ N₂ D₂ P G₃ S",
  },
  Varamu: {
    name: "Varamu",
    melakartaNum: null,
    arohanam: "S G₂ M₁ D₂ N₂ Ṡ",
    avarohanam: "Ṡ N₂ D₂ M₁ G₂ S",
  },
  Vasantha: {
    name: "Vasantha",
    melakartaNum: null,
    arohanam: "S M₁ G₃ M₁ D₂ N₃ Ṡ",
    avarohanam: "Ṡ N₃ D₂ M₁ G₃ R₁ S",
  },
  Vasanthi: {
    name: "Vasanthi",
    melakartaNum: null,
    arohanam: "S R₂ G₃ P D₁ Ṡ",
    avarohanam: "Ṡ D₁ P G₃ R₂ S",
  },
  Vijayanagari: {
    name: "Vijayanagari",
    melakartaNum: null,
    arohanam: "S R₂ G₂ M₂ P D₂ Ṡ",
    avarohanam: "Ṡ D₂ P M₂ G₂ R₂ S",
  },
  Yadukulakambhoji: {
    name: "Yadukala Kambhoji",
    melakartaNum: null,
    arohanam: "S R₂ M₁ P D₂ Ṡ",
    avarohanam: "Ṡ N₂ D₂ P M₁ G₃ R₂ S",
  },
};
